(ns cheatsheet.cheatsheet
  (:require [clojure.string :as string]
            [garden.selectors :as gs])
  (:use [lambdaisland.ornament]))


(def dev-file-names
  ["cursorless"
   "cursorless global"
   "cursorless snippets"
   "gb"
   "general"
   "chrome"
   "apple terminal"
   "finder"
   "vscode"
   "edit"
   "edit settings"
   "file extension"
   "keys"
   "text"
   "edit vocabulary"
   "websites and search engines"
   "css"
   "comment block"
   "comment documentation"
   "comment line"
   "functions"
   "functions common"
   "functions common gui active"
   "imperative"
   "keywords"
   "libraries"
   "library gui open"
   "data bool"
   "data null"
   "operators lambda"
   "operators array"
   "operators assignment"
   "cancel"
   "draft editor"
   "draft editor open"
   "mac macro"
   "dropdown"
   #_"text navigation"
   "browser"
   "file manager"
   "find and replace"
   "line commands"
   "snippets"
   "snippets open"
   "splits"
   "terminal"
   "unix utilities"
   "gaze ocr"
   "gaze ocr disambiguation"
   "menu"
   #_"notification"
   "vscode"
   "debugger"
   "symbols"
   "repeater"
   #_"github web"
   "gdb active"
   "gdb global"
   "dictation mode"
   "markdown"
   "object oriented"
   "operators bitwise"
   "operators math"
   "operators pointer"
   "command history"
   "datetimeinsert"
   "desktops"])
   

(def file-names
  ["user.letter"
   "user.number_key"
   "user.modifier_key"
   "user.special_key"
   "user.symbol_key"
   "user.arrow_key"
   "user.punctuation"
   "user.function_key"
   "formatters"
   "intellij"
   "1password"
   "1password global"
   "amethyst"
   "anaconda"
   "apple notes"
   "discord"
   "dunst"
   "eclipse"
   "mac emacs"
   "firefox"
   "git"
   "git add patch"
   "gitlab"
   "i3wm"
   "jetbrains"
   "linux keepassx linux"
   "kubectl"
   "orion"
   "outlook web"
   "win outlook win"
   "protonmail"
   "mac rstudio mac"
   "linux signal linux"
   "mac slack mac"
   "win slack win"
   "talon repl"
   "linux taskwarrior linux"
   "teams"
   "mac teams mac"
   "termite"
   "terraform"
   "thunderbird"
   "thunderbird calendar"
   "thunderbird composer"
   "thunderbird contacts"
   "thunderbird inbox"
   "thunderbird tasks"
   "tmux"
   "linux tmux linux"
   "vivaldi"
   "win windbg"
   "win windows explorer"
   "win windows terminal"
   "wsl"
   "abbreviate"
   "help"
   "help open"
   "help scope open"
   "homophones"
   "homophones open"
   "dragon mode"
   "language modes"
   "modes"
   "sleep mode wav2letter"
   "wake and sleep"
   "wake and sleep wav2letter"
   "mouse grid"
   "mouse grid always"
   "mouse grid open"
   "numbers"
   "screens"
   "win tabs"
   "win window management"
   "batch"
   "c"
   "go"
   "java"
   "javascript"
   "lua"
   "stylua"
   "php"
   "proto"
   "python"
   "r"
   "ruby"
   "rust"
   "scala"
   "sql"
   "talon"
   "terraform"
   "vimscript"
   "media"
   "microphone selection"
   "mouse"
   "mouse cursor"
   "screenshot"
   "win draft global"
   "win draft window"
   "win draft window open"
   "talon helpers"
   "chapters"
   "emoji"
   "messaging"
   "multiple cursors"
   "pages"
   "photoshop"
   "ps-menus"
   "rango"
   "rango direct clicking"
   "roam"
   "win window action"
   "win window doc"
   "hud content focus"
   "hud content toolkit"
   "hud content walkthrough"
   "hud choice commands"
   "hud commands"
   "hud widget quick choices"
   "cheatsheet"])

(def class-names 
  (->> dev-file-names
    (mapv #(string/replace % " " "-"))))

(def show-rules
  (->> class-names
    (mapv
      (fn [class-str]
        (let [id-selector (keyword (str "#" class-str))]
          [[id-selector :block]
           [(gs/+ id-selector :ul)  :block]])))
    (apply concat)
    vec))


(defstyled dev-cheatsheet :body
  [:ul :hidden]
  [:h1 :hidden]
  [:blockquote :hidden]
  show-rules)

(def my-hiccup
  [dev-cheatsheet])

(spit "dev-cheatsheet.css"
  (defined-styles))

(defined-styles)